echo "---"
echo "layout: post"
echo "title: \" \""
echo "description: \" \""
echo "modified: "
echo "tags: [  ]"
echo "image: "
echo "  feature: "
echo "  credit: "
echo "  creditlink: "
echo "---"
echo ""
